---
assembly: hg19
build_author: alexkotlar
build_date: 2023-10-11T09:19:00
chromosomes:
- chr1
- chr2
- chr3
- chr4
- chr5
- chr6
- chr7
- chr8
- chr9
- chr10
- chr11
- chr12
- chr13
- chr14
- chr15
- chr16
- chr17
- chr18
- chr19
- chr20
- chr21
- chr22
- chrM
- chrX
- chrY
database_dir: '~'
fileProcessors:
  snp:
    args: --emptyField ! --minGq .95
    program: bystro-snp
  vcf:
    args: --emptyField ! --sample %sampleList% --keepPos --keepId
    program: bystro-vcf
files_dir: '~'
statistics:
  dbSNPnameField: dbSNP.name
  exonicAlleleFunctionField: refSeq.exonicAlleleFunction
  outputExtensions:
    json: .statistics.json
    qc: .statistics.qc.tsv
    tab: .statistics.tsv
  programPath: bystro-stats
  refTrackField: ref
  siteTypeField: refSeq.siteType
temp_dir: '~'
tracks:
  outputOrder:
  - ref
  tracks:
  - build_author: alexkotlar
    build_date: 2023-10-11T09:19:00
    name: ref
    skipChromosomes:
    - chrIJSDOF
    type: reference
    utils:
    - args:
        remoteDir: http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/
        remoteFiles:
        - human_g1k_v37.fasta.gz
      name: fetch
    version: 10
version: 10

